### ISSUE TITLE
Автопарк

### ISSUE THREAD

**Issue by GitRaut** [GitRaut/HomeWork#5]
@vdetstvepil 
AutoPark

**Comment by vdetstvepil** [comment]
**Файл AutoPark.cs**
- 18 и 19 строки. Ты присваиваешь ссылку на список, а не копируешь элементы списка, который приходит в конструктор в качестве параметра, в список класса. Т.е. если ты удалишь список вне этого конструктора, то он таким же образом сотрется и в классе. Если ты изменишь список вне конструктора, он так же поменяется и в классе. Получается, что у тебя поле класса ссылается на переменную извне.
- 11-13 строки. Не ошибка, но рекомендуется писать модификаторы доступности у полей, чтоб не вводить других в заблуждение.

**Comment by vdetstvepil** [comment]
Молодец 👍 Поправь косяки и зачту.

**Comment by GitRaut** [comment]
Я исправил

**Comment by GitRaut** [comment]
@vdetstvepil

**Comment by vdetstvepil** [comment]
@GitRaut забыл, наверное, коммитнуть и пушнуть изменения в гитхаб. Последнее обновление репозитория было сделано час назад.

**Comment by GitRaut** [comment]
@vdetstvepil  Я вроде коммитнул и пушнул пишет 17 минут назад

**Comment by vdetstvepil** [comment]
@GitRaut всё равно гитхаб показывает, что в последний раз файл AutoPark.cs изменялся час назад. Может, ты забыл коммитнуть все изменения? Проверь на всякий случай. 17 минут назад обновилась только папочка obj, но не исходники.
![image](https://user-images.githubusercontent.com/53276813/141004725-a784787a-79a8-4e8a-b0d1-bee59acd657e.png)

**Comment by GitRaut** [comment]
Я только заметил, странно, я вроде коммитил и пушил но изменения не внеслись, ну ладно, я снова исправил и отправил, теперь точно видно

**Comment by vdetstvepil** [comment]
@GitRaut ага, теперь видно. А то, что ты написал, точно работает? Я просто не уверен, что можно в конструктор списка передать список, хы

**Comment by vdetstvepil** [comment]
По-моему, так делать нельзя. Лучше воспользоваться функцией AddRange или через цикл foreach поштучно передать элементы другому списку.

**Comment by vdetstvepil** [comment]
Принято.

**Comment by GitRaut** [comment]
Отлично!)
я проверил можно ли так или нет, в итоге можно и он копирует элементы списка в новый

**Comment by vdetstvepil** [comment]
о, ура! 🎉буду тоже об этом знать
